"""empty message

Revision ID: 179e6982d661
Revises: 333f533eaac9
Create Date: 2023-04-10 11:18:01.815555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179e6982d661'
down_revision = '333f533eaac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_users_post_id_posts', type_='foreignkey')
        batch_op.drop_column('image')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('fk_users_post_id_posts', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
