"""empty message

Revision ID: 194e7a4b2b83
Revises: 179e6982d661
Create Date: 2023-04-10 11:19:14.088991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194e7a4b2b83'
down_revision = '179e6982d661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
