"""empty message

Revision ID: 333f533eaac9
Revises: 9710ebb47daa
Create Date: 2023-04-10 10:53:45.747476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333f533eaac9'
down_revision = '9710ebb47daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('location')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
