"""empty message

Revision ID: 603cf6c850cc
Revises: 194e7a4b2b83
Create Date: 2023-04-10 11:21:19.209531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603cf6c850cc'
down_revision = '194e7a4b2b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
